#pragma once
#include "types.h"
#include "arena.h"
#include <cstring>

// No templates: each element type gets its own array struct, generated by
// this macro. It's still an ordinary struct with ordinary methods -- the
// macro just saves hand-copying the same three fields and two methods for
// every element type we need an array of (Field, Node*, Value). This is
// text substitution at the preprocessor level, not a class template.
//
// The array keeps a pointer to the arena it was born with, so push()
// doesn't need the arena passed in on every call.
#define DEFINE_ARRAY(NAME, ELEM)                                             \
    struct NAME {                                                            \
        ELEM* data;                                                         \
        i64 count;                                                          \
        i64 capacity;                                                       \
        Arena* arena;                                                       \
                                                                              \
        void init(Arena* a) {                                               \
            self->data = 0;                                                 \
            self->count = 0;                                                \
            self->capacity = 0;                                             \
            self->arena = a;                                                \
        }                                                                    \
                                                                              \
        void push(ELEM value) {                                             \
            if (self->count >= self->capacity) {                           \
                i64 newCap = self->capacity == 0 ? 4 : self->capacity * 2;   \
                ELEM* newData = (ELEM*)self->arena->alloc(                   \
                    newCap * (i64)sizeof(ELEM), (i64)alignof(ELEM));         \
                if (self->data != 0 && self->count > 0) {                   \
                    memcpy(newData, self->data,                             \
                           (u64)(self->count * (i64)sizeof(ELEM)));          \
                }                                                            \
                self->data = newData;                                       \
                self->capacity = newCap;                                    \
            }                                                                \
            self->data[self->count] = value;                                \
            self->count = self->count + 1;                                  \
        }                                                                    \
                                                                              \
        ELEM& at(i64 i) { return self->data[i]; }                           \
    }
